Fintech/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from account import views as account_views
# from reports import views as reports_views
from groups import views as group_views
from messaging.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^home/', account_views.home, name='home'),
    url(r'^investor_info/', account_views.investor_info, name='investor_info'),
    url(r'^company_info/', account_views.company_info, name='company_info'),
    url(r'^signup/', account_views.signupform, name='signup'),
    url(r'^login/', account_views.log, name='login'),
    url(r'^auth/', account_views.auth),
    url(r'^showdata/', account_views.showdata),
    url(r'^logout/', account_views.loggedout, name = 'logout'),
    url(r'^loggedin/', account_views.loggedin, name='loggedin'),
    url(r'^invalid/', account_views.invalid),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'groups/$', group_views.groupHome, name = 'groups'),
    url(r'makeGroups/$', group_views.submit_groups, name = 'makeGroups'),
    url(r'viewGroups/$', group_views.view_groups, name = 'viewGroups'),
    url(r'leaveGroups/$', group_views.leave_groups),
    url(r'selectGroupToChange/$', group_views.view_groups_for_adding, name= 'selectGroup'),
    url(r'selectMembersToAdd/$', group_views.select_members_to_add, name = 'selectMembers'),
    url(r'addMembers/$', group_views.add_members, name = 'addMembers'),
    url(r'invalidSubmitGroup/$', group_views.invalid_submit_group),
    url(r'groupSuccessPage/$', group_views.success),

    #SITE MANAGER GROUP URLS
    url(r'groupHomeSiteManager/$', group_views.groupHomeSiteManager, name = 'groupHomeSiteManager'),
    url(r'deleteGroupsSiteManager/$', group_views.delete_groups_site_manager),
    url(r'viewGroupsSiteManager/$', group_views.view_groups_site_manager, name = 'viewGroupsSiteManager'),
    url(r'selectGroupToAddMembersSiteManager/$', group_views.view_groups_for_adding_site_manager, name = 'selectGroupToAddMembersSiteManager'),
    url(r'selectMembersToAddSiteManager/$', group_views.select_members_to_add_site_manager),
    url(r'addMembersSiteManager/$', group_views.add_members_site_manager, name = 'addMembersSiteManager'),
    url(r'selectGroupToDeleteMembersSiteManager/$', group_views.view_groups_for_deleting_site_manager, name = 'selectGroupToDeleteMembersSiteManager'),
    url(r'selectMembersToDeleteSiteManager/$', group_views.select_members_to_delete_site_manager),
    url(r'deleteMembersSiteManager/$', group_views.delete_members_site_manager),
    url(r'revokeSm/$', account_views.revoke_sm),
    url(r'suspendUser/$', account_views.sus_user),
    url(r'makeSiteManager/$', account_views.make_sm),

    url(r'messageHome/$', messageHome, name= 'messaging'),
    url(r'makeMessages/$', new_messages, name = 'makeMessages'),
    url(r'makeGroupMessages/$', message_groups, name = 'makeGroupMessages'),
    url(r'viewMessages/$', view_messages, name = 'viewMessages'),
    url(r'deleteMessages/$', delete_messages),
    url(r'invalidSubmitMessage/$', invalid_submit_message),
    url(r'messageSuccessPage/$', success),
    # url(r'enterPrivateKey/$', enter_password),
    url(r'decryptMessages/$', decrypt_messages),
    url(r'^fdaLogin/$', account_views.fdalogin),
    url(r'^viewReports/$', account_views.view_reports),
    url(r'^viewOne/$', account_views.view_one),
    url(r'^getEncrypt/$', account_views.get_encrypt),
    url(r'^$', account_views.index)
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reports/urls.py
from django.conf.urls import url
from .views import IndexView, ReportDetailView, ReportUpdate, ReportCreate, ReportDelete, CompanyfileCreate, addFile
# from . import views
from django.conf.urls.static import static
from django.middleware.http import ConditionalGetMiddleware
from django.views.generic import RedirectView


app_name = 'reports'

urlpatterns = [

    # /modelforms/
    url(r'^$', IndexView.as_view(), name='index'),

    url(r'^(?P<pk>[0-9]+)/$', ReportDetailView.as_view(), name='detail'),

    # modelforms/product/entry
    url(r'^report/add/$', ReportCreate.as_view(), name='report-add'),

    url(r'^companyfile/$', CompanyfileCreate.as_view(), name='companyfile_form'),

    # modelforms/product/2
    url(r'^report/(?P<pk>[0-9]+)/$', ReportUpdate.as_view(), name='report-update'),

    url(r'^(?P<pk>[0-9]+)/addfiles/$', addFile),
    # url(r'/addfiles/$', addFile),



    # modelforms/product/(?P<pk>[0-9]+)/delete
    url(r'^report/(?P<pk>[0-9]+)/delete/$', ReportDelete.as_view(), name='report-delete'),

    # # /users/signup:url to take the input from the user
    # url(r'^newreport/$', views.newreport, name='newreport'),
    # # /users/showdata:url to display the list of users stored on the database
    # url(r'^showreportdata$', views.showreportdata, name='showreportdata'),
]

reports/models.py
from django.db import models
from django.core.urlresolvers import reverse
from account.models import CustomUser
from django.contrib.auth.models import User




def content_file_name(instance, filename):
    return '/'.join(['report', str(instance.report_id), filename])



class Report(models.Model):
    created_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=1, editable=False)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    company_name=models.CharField(max_length=255)
    ceo_name=models.CharField(max_length=255)
    company_phone=models.CharField(max_length=255)
    company_email = models.CharField(max_length=255)
    company_location=models.CharField(max_length=255)
    company_country=models.CharField(max_length=255)
    sector=models.CharField(max_length=255)
    industry=models.CharField(max_length=255)
    current_projects=models.TextField()
    private_report = models.BooleanField(default=False, blank=True)
    #files_attached = models.FileField(blank=True, null=True, upload_to=content_file_name)
    # files_attached = models.FileField(blank=True, null=True, upload_to="uploads/")


    # returns the name of the company the report is for
    def get_absolute_url(self):
        return reverse('reports:detail', kwargs={'pk': self.pk})


    def __str__(self):
        return self.company_name


class Companyfile(models.Model):
    report = models.ForeignKey(Report, on_delete=models.CASCADE, editable=False)
    # company_filename = models.CharField(max_length=100)
    cfile = models.FileField(blank=True, null=True, upload_to=content_file_name)
    encrypted = models.BooleanField(default=False)






class Investorfile(models.Model):
    report = models.ForeignKey(Report, on_delete=models.CASCADE, editable=False)
    # investor_filename = models.CharField(max_length=100)
    ifile = models.FileField(blank=True, null=True, upload_to=content_file_name)
    encrypted = models.BooleanField(default=False)

reports/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponseRedirect, request, HttpResponseForbidden
from django.utils.decorators import method_decorator

from reports.models import Companyfile, Investorfile
from .models import Report
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from .forms import ReportForm, CompanyFilesFormSet, CompanyfileForm, InvestorfileForm
from account.models import CustomUser
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView, FormMixin
from django.views.generic.list import ListView, View
from django.core.urlresolvers import reverse_lazy, reverse
from django.views.generic import ListView, DetailView
from .models import CustomUser
from django.contrib.auth.models import User
from django.db.models import Q
from groups.models import Group
from django.forms import inlineformset_factory, ClearableFileInput
from django.db import transaction
from django.forms import formsets
from django.views.decorators.http import require_http_methods

# view for the index page
class IndexView(ListView):
    # name of the object to be used in the index.html
    context_object_name = 'report_list'
    template_name = 'reports/html5up/reports.html'

    # def get_queryset(self):
    #     all_reports=Report.objects.all()
    #     if(not my_user(self.request).is_SiteManager):
    #         all_reports=all_reports.filter(created_by=my_user(self.request))
    #     query = self.request.GET.get('q')
    #     if query:
    #         return all_reports.filter(Q(company_name__icontains=query))
    #
    #     else:
    #         return all_reports

    def get_queryset(self):
        all_reports = Report.objects.all()
        if (not my_user(self.request).is_SiteManager):
            if(all_reports):
                query=Q()
                query |= Q(created_by=my_user(self.request))
                all_groups = Group.objects.all().filter(members=my_user(self.request))
                for group in all_groups:
                    for member in group.members.all():
                        query|=Q(created_by=member)
                query|=Q(private_report=False)
                all_reports=all_reports.filter(query)

        company_name = self.request.GET.get('company_name')
        ceo_name=self.request.GET.get('ceo_name')
        created_at = self.request.GET.get('created_at')
        company_phone = self.request.GET.get('company_phone')
        company_email= self.request.GET.get('company_email')
        company_location= self.request.GET.get('company_location')
        company_sector= self.request.GET.get('company_sector')
        company_industry= self.request.GET.get('company_industry')
        company_projects= self.request.GET.get('company_projects')

        option = self.request.GET.get('option')

        if(option=='and'):
            if (company_name and not company_name==''):
                all_reports=all_reports.filter(company_name__icontains=company_name)
            if (ceo_name and not ceo_name == ''):
                all_reports = all_reports.filter(ceo_name__icontains=ceo_name)
            if (created_at and not created_at==''):
                all_reports=all_reports.filter(created_at__icontains=created_at)
            if (company_phone and not company_phone==''):
                all_reports =all_reports.filter(company_phone__icontains=company_phone)
            if (company_email and not company_email==''):
                all_reports =all_reports.filter(company_email__icontains=company_email)
            if (company_location and not company_location==''):
                all_reports =all_reports.filter(company_location__icontains=company_location)
            if (company_sector and not company_sector==''):
                all_reports =all_reports.filter(sector__icontains=company_sector)
            if (company_industry and not company_industry==''):
                all_reports =all_reports.filter(industry__icontains=company_industry)
            if (company_projects and not company_projects==''):
                all_reports =all_reports.filter(current_projects__icontains=company_projects)
        elif(option=='or'):
            query=Q()
            if(company_name):
                query|=Q(company_name__icontains=company_name)
            if(ceo_name):
                query|=Q(ceo_name__icontains=ceo_name)
            if(created_at):
                query|=Q(created_at__icontains=created_at)
            if(company_phone):
                query|=Q(company_phone__icontains=company_phone)
            if(company_email):
                query|=Q(company_email__icontains=company_email)
            if(company_location):
                query|=Q(company_location__icontains=company_location)
            if(company_sector):
                query|=Q(sector__icontains=company_sector)
            if(company_industry):
                query|=Q(industry__icontains=company_industry)
            if(company_projects):
                query|=Q(current_projects__icontains=company_projects)
            all_reports=all_reports.filter(query)

        return all_reports


def my_user(request):
    user = None
    if request.user.is_authenticated():
        user = request.user
        # return username
    return CustomUser.objects.all().filter(user=user)[0]
    #     return CustomUser.objects.all()


# detail view to show all fields for specific form
class ReportDetailView(FormMixin, DetailView):
    model = Report
    template_name = 'reports/detail.html'
    # if CustomUser.objects.get(user=self.request.user):
    # else:




    def get_form_class(self):
        # if request.user.is_authenticated():
        user = CustomUser.objects.get(user=self.request.user)
        userType = user.user_type
        if userType == 'I':
            return InvestorfileForm
        else:
            return CompanyfileForm



    def get_success_url(self):
        return reverse('reports:detail', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super(ReportDetailView, self).get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


    def form_valid(self, form):
        user = CustomUser.objects.get(user=self.request.user)
        userType = user.user_type
        if userType == 'C':
            Companyfile.instance = self.object
        else:
            Investorfile.instance = self.object

        return super(ReportDetailView, self).form_valid(form)

    # def get_context_data(self, **kwargs):
    #     context = super(ReportCreate, self).get_context_data(**kwargs)
    #     context['form'] = CompanyfileCreate
    #     return context
    #
    # # @require_http_methods(["POST"])
    # def post(self, request, *args, **kwargs):
    #     return CompanyfileCreate.post(self, request, *args, **kwargs)



class CompanyfileCreate(CreateView):
    model = Companyfile
    form_class = CompanyfileForm
    template_name = 'reports/companyfile_form.html'
    success_url = reverse_lazy('reports:index')

    def form_valid(self, form):
        # form.ReportCreate()

        return super().form_valid(form)

class InvestorfileCreate(CreateView):
    model = Investorfile
    form_class = InvestorfileForm
    template_name = 'reports/investorfile_form.html'
    success_url = reverse_lazy('reports:index')
    def form_valid(self, form):
        # form.ReportCreate()
        return super().form_valid(form)


# view for the new report entry page
class ReportCreate(CreateView):
    model = Report
    form_class = ReportForm
    # object = None
    template_name = 'reports/report_form.html'
    # success_url =
    # success_url = 'reports/detail.hmtl'
#     # the fields become the entry rows in the generated form
#     fields = ['company_name', 'ceo_name', 'company_phone', 'company_email',
#               'company_location', 'company_country', 'sector', 'industry',
#               'current_projects', 'private_report']     #, 'files_attached']
#
    # @method_decorator(login_required)
    # def dispatch(self, *args, **kwargs):
    #     return super(ReportCreate, self).dispatch(*args, **kwargs)


    def get_context_data(self, **kwargs):
        context = super(ReportCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['companyfiles'] = CompanyFilesFormSet(self.request.POST)
            # context['investorfiles_form'] = InvestorFilesFormSet(self.request.POST, self.request.FILES)
        else:
            context['companyfiles'] = CompanyFilesFormSet()
            # context['investorfiles_form'] = InvestorFilesFormSet()
        return context


    def form_valid(self, form):
        context = self.get_context_data()
        companyfiles = context['companyfiles']

        if form.is_valid():
            self.object = form.save(commit=False)
            userC = CustomUser.objects.get(user=self.request.user)
            self.object.created_by = userC
            self.object = form.save()
        if companyfiles.is_valid():
            companyfiles.instance = self.object
            companyfiles.save(commit=False)
            obj_report = form.instance
            boolean_value = self.request.POST.get('companyfile_set-0-encrypted')
            if boolean_value == 'on':
                a = bool('true')
            else:
                a = bool('')
            # file = self.request.FILES.get('companyfile_set-0-cfile')

reports/templates/reports/companyfile_form.html
<form action="" method="POST">{% csrf_token %}
  {{ form.as_p }}
</form>

reports/templates/reports/detail.html
<!DOCTYPE HTML>
<!--
    TXT by HTML5 UP
    html5up.net | @ajlkn.
    Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'messaging/css/main.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'messaging/css/ie8.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'messaging/css/font-awesome.min.css' %}" />
<html>
    <head>
        <title>Lokahi Fintech</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
        <link rel="stylesheet" href="assets/css/main.css" />
        <!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
        <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css">
        <script type="text/javascript">
            $(function() {
                $(".inline.{{ companyfiles_form.prefix }}").formset({
                    prefix: "{{ companyfiles_form.prefix }}",
                })
                $(".inline.{{ investorfiles_form.prefix }}").formset({
                    prefix: "{{ investorfiles_form.prefix }}",
                })
            })
        </script>
    </head>
    <body class="homepage">
        <div id="page-wrapper">

            <!-- Header -->
                <header id="header">
                    <div class="logo container">
                        <div>
                            <h1><a id="logo">{{ report.company_name }} Report</a></h1>
                        </div>
                    </div>
                </header>

            <!-- Nav -->
                <nav id="nav">
                    <ul>
                        <li><a href={% url 'loggedin' %}>Home</a></li>
                        <li class = "current"><a href = "{% url 'reports:index'%}" >Reports</a></li>
                        <li><a href = {% url 'groups' %}>Groups</a></li>
                        <li><a href = {% url 'messaging' %}>Messaging</a></li>
                        <li><a href= {% url 'logout' %}>LOG OUT</a></li>
                    </ul>
                </nav>
            <!-- Main -->
                <div id="main-wrapper">{#<a href="{% url 'reports:detail' report.id %}"></a>#}

    <ul>
        <br>
        <table class="table">
            <tr><td><div style = "padding-left: 40px">Created By: {{ report.created_by }}</div></td></tr>
            <tr><td><div style = "padding-left: 40px">Company Phone: {{ report.company_phone }}</div></td></tr>
            <tr><td><div style = "padding-left: 40px">CEO: {{ report.ceo_name }}</div></td></tr>
            <tr><td><div style = "padding-left: 40px">Company Email: {{ report.company_email }}</div></td></tr>
            <tr><td><div style = "padding-left: 40px">Company Location: {{ report.company_location }}</div></td></tr>
            <tr><td><div style = "padding-left: 40px">Company Country: {{ report.company_country }}</div></td></tr>
            <tr><td><div style = "padding-left: 40px">Sector: {{ report.sector }}</div></td></tr>
            <tr><td><div style = "padding-left: 40px">Industry: {{ report.industry }}</div></td></tr>
            <tr><td><div style = "padding-left: 40px">Current Projects: {{ report.current_projects }}</div></td></tr>
            <tr><td><div style = "padding-left: 40px">Private Report: {{ report.private_report }}</div></td></tr>


            <tr><td><div style = "padding-left: 40px">Created At: {{ report.created_at }}</div></td></tr>
        </table>


        <div class="container">
            <h3>Company Files Attached:</h3>
            <table class="table">
                {% if report.companyfile_set%}
                    <tbody>
                        {% for file in report.companyfile_set.all %}
                            {% if file.encrypted == 0 %}
                          <tr>

                              <td><div style = "padding-left: 40px"> File Name: <a href="{{ file.cfile.url }}" download> <strong> {{  file.cfile.name }}</strong></a></div></td>
                          </tr>

                            {% else %}
                                <tr>
                                    <td><div style = "padding-left: 40px">File Name: <strong> {{  file.cfile.name }}</strong></div></td>
                                </tr>
                            {% endif %}


                        {% empty %}
                            <tr><td><div style = "padding-left: 40px">None</div></td></tr>
                        {% endfor %}
                    </tbody>
                {% else %}
{#                    <h1>hello</h1>#}
                    <tr><td><div style = "padding-left: 40px">None</div></td></tr>
                {% endif %}
            </table>
        </div>



        <div class="container">
            <h3>Investor Files Attached:</h3>
            <table class="table">
                {% if report.investorfile_set%}
                    <tbody>
                        {% for file in report.investorfile_set.all %}
                            {% if file.encrypted == 0 %}
                          <tr>

                              <td><div style = "padding-left: 40px"> File Name: <a href="{{ file.ifile.url }}" download> <strong> {{  file.ifile.name }}</strong></a></div></td>
                          </tr>

                            {% else %}
                                <tr>
                                    <td><div style = "padding-left: 40px">File Name: <strong> {{  file.ifile.name }}</strong></div></td>
                                </tr>
                            {% endif %}


                        {% empty %}
                            <tr><td><div style = "padding-left: 40px">None</div></td></tr>
                        {% endfor %}
                    </tbody>
                {% else %}
{#                    <h1>hello</h1>#}
                    <tr><td><div style = "padding-left: 40px">None</div></td></tr>
                {% endif %}
            </table>


        </div>
<div style="padding-left: 40px">
     <form class="form-horizontal" action="./addfiles/"  method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                {{ form.as_p }}
            </div>
{#            <input type="hidden" name="reportID" value="{{ report.id }}">#}

            <input type="submit" value="Upload File"/>
        </form>
</div>


{#        <form action="" method="post">#}
{#            <fieldset>#}
{#                <legend>Add an Investor File</legend>#}
{#                {{ investorfiles_form.management_form }}#}
{#                {{ investorfiles_form.non_form_errors }}#}
{#                {% for form in investorfiles_form %}#}
{#                    {{ form.id }}#}
{#                    <div class="inline {{ investorfiles_form.prefix }}">#}
{#                        {{ form.investor_file.errors }}#}
{#                        {{ form.investor_file.label_tag }}#}
{#                        {{ form.investor_file }}#}
{#                        {{ form.encrypted.errors }}#}
{#                        {{ form.encrypted.label_tag }}#}
{#                        {{ form.encrypted }}#}
{#                    </div>#}
{#                {% endfor %}#}
{#            </fieldset>#}
{#        </form>#}






    <div style = "text-align: center">
    <form action="{% url 'reports:report-delete' report.id %}" method="post" style="display: inline;">
            {% csrf_token %}
            <input type="hidden" name="report_id" value="{{ report.id }}"/>
        {% if user.customuser.is_SiteManager %}
            <button type="submit" class="btn btn-danger btn-xs">
                <span class="glyphicon glyphicon-remove"></span> Delete
            </button>
        {% endif %}
    </form>


    <a href="{% url 'reports:report-update' report.id %}" style="display: inline; padding-left: 40px">
        {% if user.customuser.is_SiteManager %}
            <button type="" class="btn btn-default btn-sm">Update</button>
        {% endif %}
    </a>

</div>
<br>
<div style = "text-align: center">
    <a href="{% url 'reports:index' %}"<button type="" class="btn btn-default btn-sm">Return to Reports Home</button>
    </div>
        </li>

    </ul>
                <footer id="footer">


                    <!-- Copyright -->
                            <ul class="copyright">
                                <li>&copy; Lokahi Fintech. All rights reserved</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
                            </ul>
                        </div>

                </footer>

            </div>

        <!-- Scripts -->
            <script src="assets/js/jquery.min.js"></script>
            <script src="assets/js/jquery.dropotron.min.js"></script>
            <script src="assets/js/skel.min.js"></script>
            <script src="assets/js/skel-viewport.min.js"></script>
            <script src="assets/js/util.js"></script>
            <!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
            <script src="assets/js/main.js"></script>

    </body>
</html>

reports/templates/reports/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger la">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

reports/templates/reports/index.html
<!DOCTYPE HTML>
<!--
    TXT by HTML5 UP
    html5up.net | @ajlkn.
    Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'messaging/css/main.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'messaging/css/ie8.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'messaging/css/font-awesome.min.css' %}" />
<html>
    <head>
        <title>Lokahi Fintech</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
        <link rel="stylesheet" href="assets/css/main.css" />
        <!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
        <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css">
    </head>
    <body class="homepage">
        <div id="page-wrapper">

            <!-- Header -->
                <header id="header">
                    <div class="logo container">
                        <div>
                            <h1><a id="logo">Reports</a></h1>
                        </div>
                    </div>
                </header>

            <!-- Nav -->
                <nav id="nav">
                    <ul>
                        <li><a href={% url 'loggedin' %}>Home</a></li>
                        <li class = "current"><a href = >Reports</a></li>
                        <li><a href = {% url 'groups' %}>Groups</a></li>
                        <li><a href = {% url 'messaging' %}>Messaging</a></li>
                        <li><a href= {% url 'logout' %}>LOG OUT</a></li>
                    </ul>
                </nav>
            <!-- Main -->
                <div id="main-wrapper">
                    {% if report_list %}



                        <h1>List of All Company Reports</h1>
                    {#    <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'reports:index' %}">#}
                    {#                <div class="form-group">#}
                    {#                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">#}
                    {#                </div>#}
                    {#                <button type="submit" class="btn btn-default">Search</button>#}
                    {#    </form>#}
                        <style>
                            input[type=text]
                            {
                                width: 130px;
                                box-sizing: border-box;
                                border: 2px solid #ccc;
                                border-radius: 4px;
                                font-size: 16px;
                                background-color: white;
                                background-image: url('searchicon.png');
                                background-position: 10px 10px;
                                background-repeat: no-repeat;
                                padding: 12px 20px 12px 40px;
                                -webkit-transition: width 0.4s ease-in-out;
                                transition: width 0.4s ease-in-out;
                            }

                            input[type=text]:focus
                            {
                                width: 70%;
                            }
                        </style>


                        <form id="searchform" action="{% url 'reports:index' %}" method="get" autocomplete="on" >
                            <button class="searchbutton" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                            <input id="searchbox" type="text" name="q" type="text" placeholder="Search...">
                        </form>



                        <ul>
                            {% for report in report_list %}
                                <li><a href="{% url 'reports:detail' report.id %}">{{ report.company_name }}</a></li>
                                <!--<li><a download class="list-group-item list-group-item-action" href=</li> -->
                            {% endfor %}
                        </ul>


                    {% else %}
                        <h1>No report entries found on the database.</h1>

                    {% endif %}

                    <form action="{% url 'reports:report-add'  %}" method="post">
                             {% csrf_token %}
                             <button type="submit" class="btn btn-default btn-sm">Create New Report</button>
                    </form>