Fintech/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from account import views as account_views
# from reports import views as reports_views
from groups import views as group_views
from messaging.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^home/', account_views.home, name='home'),
    url(r'^investor_info/', account_views.investor_info, name='investor_info'),
    url(r'^company_info/', account_views.company_info, name='company_info'),
    url(r'^signup/', account_views.signupform, name='signup'),
    url(r'^login/', account_views.log, name='login'),
    url(r'^auth/', account_views.auth),
    url(r'^showdata/', account_views.showdata),
    url(r'^logout/', account_views.loggedout, name = 'logout'),
    url(r'^loggedin/', account_views.loggedin, name='loggedin'),
    url(r'^invalid/', account_views.invalid),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'groups/$', group_views.groupHome, name = 'groups'),
    url(r'makeGroups/$', group_views.submit_groups, name = 'makeGroups'),
    url(r'viewGroups/$', group_views.view_groups, name = 'viewGroups'),
    url(r'leaveGroups/$', group_views.leave_groups),
    url(r'selectGroupToChange/$', group_views.view_groups_for_adding, name= 'selectGroup'),
    url(r'selectMembersToAdd/$', group_views.select_members_to_add, name = 'selectMembers'),
    url(r'addMembers/$', group_views.add_members, name = 'addMembers'),
    url(r'invalidSubmitGroup/$', group_views.invalid_submit_group),
    url(r'groupSuccessPage/$', group_views.success),

    #SITE MANAGER GROUP URLS
    url(r'groupHomeSiteManager/$', group_views.groupHomeSiteManager, name = 'groupHomeSiteManager'),
    url(r'deleteGroupsSiteManager/$', group_views.delete_groups_site_manager),
    url(r'viewGroupsSiteManager/$', group_views.view_groups_site_manager, name = 'viewGroupsSiteManager'),
    url(r'selectGroupToAddMembersSiteManager/$', group_views.view_groups_for_adding_site_manager, name = 'selectGroupToAddMembersSiteManager'),
    url(r'selectMembersToAddSiteManager/$', group_views.select_members_to_add_site_manager),
    url(r'addMembersSiteManager/$', group_views.add_members_site_manager, name = 'addMembersSiteManager'),
    url(r'selectGroupToDeleteMembersSiteManager/$', group_views.view_groups_for_deleting_site_manager, name = 'selectGroupToDeleteMembersSiteManager'),
    url(r'selectMembersToDeleteSiteManager/$', group_views.select_members_to_delete_site_manager),
    url(r'deleteMembersSiteManager/$', group_views.delete_members_site_manager),
    url(r'revokeSm/$', account_views.revoke_sm),
    url(r'suspendUser/$', account_views.sus_user),
    url(r'makeSiteManager/$', account_views.make_sm),

    url(r'messageHome/$', messageHome, name= 'messaging'),
    url(r'makeMessages/$', new_messages, name = 'makeMessages'),
    url(r'makeGroupMessages/$', message_groups, name = 'makeGroupMessages'),
    url(r'viewMessages/$', view_messages, name = 'viewMessages'),
    url(r'deleteMessages/$', delete_messages),
    url(r'invalidSubmitMessage/$', invalid_submit_message),
    url(r'messageSuccessPage/$', success),
    # url(r'enterPrivateKey/$', enter_password),
    url(r'decryptMessages/$', decrypt_messages),
    url(r'^fdaLogin/$', account_views.fdalogin),
    url(r'^viewReports/$', account_views.view_reports),
    url(r'^viewOne/$', account_views.view_one),
    url(r'^getEncrypt/$', account_views.get_encrypt),
    url(r'^$', account_views.index)
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reports/urls.py
from django.conf.urls import url
from .views import IndexView, ReportDetailView, ReportUpdate, ReportCreate, ReportDelete, CompanyfileCreate, addFile
# from . import views
from django.conf.urls.static import static
from django.middleware.http import ConditionalGetMiddleware
from django.views.generic import RedirectView


app_name = 'reports'

urlpatterns = [

    # /modelforms/
    url(r'^$', IndexView.as_view(), name='index'),

    url(r'^(?P<pk>[0-9]+)/$', ReportDetailView.as_view(), name='detail'),

    # modelforms/product/entry
    url(r'^report/add/$', ReportCreate.as_view(), name='report-add'),

    url(r'^companyfile/$', CompanyfileCreate.as_view(), name='companyfile_form'),

    # modelforms/product/2
    url(r'^report/(?P<pk>[0-9]+)/$', ReportUpdate.as_view(), name='report-update'),

    url(r'^(?P<pk>[0-9]+)/addfiles/$', addFile),
    # url(r'/addfiles/$', addFile),



    # modelforms/product/(?P<pk>[0-9]+)/delete
    url(r'^report/(?P<pk>[0-9]+)/delete/$', ReportDelete.as_view(), name='report-delete'),

    # # /users/signup:url to take the input from the user
    # url(r'^newreport/$', views.newreport, name='newreport'),
    # # /users/showdata:url to display the list of users stored on the database
    # url(r'^showreportdata$', views.showreportdata, name='showreportdata'),
]

account/models.py
from django.db import models
from django.contrib.auth.models import User

class CustomUser(models.Model):
    user = models.OneToOneField(User)
    type_choice = (
        ("C", "Company User"),
        ('I', "Investor User"),
    )
    is_SiteManager = models.BooleanField(default=False)
    user_type = models.CharField(max_length=1, choices=type_choice, default='C')
    publicKey=models.TextField(blank=True)
    privateKey=models.TextField(blank=True)

#this returns the name of the user when the object of user is printed
    def __str__(self):
        sm = "False"
        if self.user.customuser.is_SiteManager:
            sm = "True"
            return self.user.get_username()+ ": " + "Site Manager"
        #return self.user.get_username() + ": " + (self.user.customuser.get_user_type_display()) + sm
        return self.user.get_username() + ": " + (self.user.customuser.get_user_type_display())

account/forms.py
#importing forms
from django import forms
from .models import CustomUser
#creating our forms


class SignupForm(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = ('user_type',)

account/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
from django.template.context_processors import csrf
from .forms import SignupForm
from .models import CustomUser
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages
from django.http import JsonResponse
from messaging import views as messaging_views
from django.views.decorators.csrf import csrf_exempt
from reports.models import Report
from django.db.models import Q
from groups.models import Group
# Create your views here.


def signupform(request):
    #if form is submitted
    if request.method == 'POST':
        #will handle the request later
        form = SignupForm(request.POST)

        #checking the form is valid or not
        if form.is_valid():
            username = request.POST["username"]
            email = request.POST["email"]
            password = request.POST["password"]
            user_type = request.POST["user_type"]
            if not User.objects.filter(username=username).exists():
                user = User.objects.create_user(username, email=email, password=password)
                user.save()
                uinfo = CustomUser()
                uinfo.user = user
                uinfo.user_type = user_type
                key = messaging_views.key_generator()
                publicKey = messaging_views.get_public_key(key)
                privateKey = messaging_views.get_private_key(key)
                uinfo.publicKey = publicKey
                uinfo.privateKey = privateKey
                uinfo.save()
                uinfo.save()
                return render(request, 'html5up/login.html')  # Redirect after POST
            else:
                messages.error(request, 'username is taken')
                return HttpResponseRedirect('/signup')
            # return render(request, 'result.html', {
            # 		'username': form.cleaned_data['username'],
            # 	})

    else:
        #creating a new form
        form = SignupForm()

    #returning form
    return render(request, 'html5up/signup.html', {'form':form})


@login_required
def showdata(request):
    all_users = User.objects.all()
    return render(request, 'showdata.html', {'all_users': all_users, })


def home(request):
    c = {}
    c.update(csrf(request))
    return render(request, 'html5up/index.html', c)


def investor_info(request):
    c = {}
    c.update(csrf(request))
    return render(request, 'html5up/investor_info.html', c)


def company_info(request):
    c = {}
    c.update(csrf(request))
    return render(request, 'html5up/company_info.html', c)


def log(request):
    c = {}
    c.update(csrf(request))
    if not User.objects.filter(username="sm").exists():
        user = User.objects.create_user(username='sm', email='smEmail', password='sm')
        user.save()
        uinfo = CustomUser()
        uinfo.user = user
        uinfo.user_type = 'C'
        uinfo.is_SiteManager = True
        key = messaging_views.key_generator()
        publicKey = messaging_views.get_public_key(key)
        privateKey = messaging_views.get_private_key(key)
        uinfo.publicKey = publicKey
        uinfo.privateKey = privateKey
        uinfo.save()
    return render(request, 'html5up/login.html', c)


def auth(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            return HttpResponseRedirect('/loggedin')
        else:
            return HttpResponseRedirect('/invalid')
    else:
        return HttpResponseRedirect('/invalid')


@login_required
def loggedin(request):
    c = {}
    c.update(csrf(request))
    if request.user.customuser.is_SiteManager:
        return render(request,'html5up/sitemanager.html', c)
    if request.user.customuser.user_type == 'I':
        return render(request, 'html5up/investor.html', c )
    elif request.user.customuser.user_type == 'C':
        return render(request, 'html5up/company.html', c )
    else:
        return render(request, 'html5up/investor.html', c)


def invalid(request):
    return render(request, 'html5up/invalid.html')


def loggedout(request):
    logout(request)
    return render(request, 'html5up/loggedout.html')


@user_passes_test(lambda u: u.customuser.is_SiteManager)
def del_user(request):
    username = request.POST["username"]
    if User.objects.filter(username=username).exists():
        user = User.objects.get(username=username)
    # if user.DoesNotExist:
    #     messages.info(request, "User does not exist",extra_tags='safe')
    # else:
        user.delete()
        messages.info(request, "User deleted Successfully")
    else:
        messages.info(request, "User does not exist")
    return HttpResponseRedirect('/loggedin')


@user_passes_test(lambda u: u.customuser.is_SiteManager)
def sus_user(request):
    username = request.POST["username"]
    if User.objects.filter(username=username).exists():
        user = User.objects.get(username=username)
        if user.customuser.is_SiteManager:
            messages.info(request, "This user is a SiteManager and thus you cannot change his/her status")
        elif user.is_active:
            user.is_active = False
            user.save()
            messages.info(request, "User suspended Successfully")
        else:
            user.is_active = True
            user.save()
            messages.info(request, "The User is no longer suspended")
    else:
        messages.info(request, "User does not exist")
    return HttpResponseRedirect('/loggedin')

@user_passes_test(lambda u: u.customuser.is_SiteManager)
def make_sm(request):
    username = request.POST["username"]
    if User.objects.filter(username=username).exists():
        user = User.objects.get(username=username)
        if user.customuser.is_SiteManager:
            messages.info(request, "This user is already a Site Manager")
        else:
            user.customuser.is_SiteManager = True
            user.customuser.save()
            messages.info(request, "User is now a Site Manager")
    else:
        messages.info(request, "User does not exist")
    return HttpResponseRedirect('/loggedin')


@user_passes_test(lambda u: u.customuser.is_SiteManager)
def revoke_sm(request):
    request.user.customuser.is_SiteManager = False
    request.user.customuser.save()
    return HttpResponseRedirect('/loggedin')


@csrf_exempt
def fdalogin(data):
    username = data.POST["username"]
    password = data.POST["password"]
    user = authenticate(username = username, password = password)
    if user is not None and user.is_active:
        return JsonResponse({'login':True})
    else:
        return JsonResponse({'login':False})


def get_reports(user):
    all_reports = Report.objects.all()
    if not user.customuser.is_SiteManager:
        if all_reports:
            query = Q()
            query |= Q(created_by=user.customuser)
            all_groups = Group.objects.all().filter(members=user.customuser)
            for group in all_groups:
                for member in group.members.all():
                    query |= Q(created_by=member)
            query |= Q(private_report=False)
            all_reports = all_reports.filter(query)
    return all_reports

@csrf_exempt
def view_reports(data):
    obs = User.objects.all().filter(username=data.POST['user'])
    for x in obs:
        user = x
    report_name = []
    all_reports = get_reports(user)
    for x in all_reports:
        report_name.append("Company Name: " + x.company_name + "  Owner: " + x.created_by.user.username + "   ID: " + str(x.id))
    return JsonResponse({'reports': report_name})


@csrf_exempt
def view_one(data):
    #report = Report.objects.all().filter(id=data.POST['id'])
    report = None
    obs = User.objects.all().filter(username=data.POST['user'])
    for x in obs:
        user = x
    all_reports = get_reports(user)
    for one in all_reports:
        if str(one.id) == data.POST['id']:
            report = one
    if report is None:
        dictionary = {'COMPANY': "Does not exist"}
    else:
        dictionary = {'CREATED BY': report.created_by.user.username, 'COMPANY': report.company_name, 'PHONE' : report.company_phone, 'EMAIL': report.company_email,
                      'LOCATION': report.company_location, 'COUNTRY': report.company_country, 'SECTOR': report.sector, 'INDUSTRY': report.industry, 'CEO':report.ceo_name,
                        'PROJECTS': report.current_projects}
        fileList = []
        for file in report.companyfile_set.all():
            if file is not None:
                fileList.append(file.cfile.name)
        for file in report.investorfile_set.all():
            if file is not None:
                fileList.append(file.ifile.name)
        dictionary['files'] = fileList
    return JsonResponse(dictionary)

@csrf_exempt
def get_encrypt(request):
    report = None
    obs = User.objects.all().filter(username=request.POST['user'])
    for x in obs:
        user = x
    all_reports = get_reports(user)
    for one in all_reports:
        if str(one.id) == request.POST['id']:
            report = one
    this_file = None
    if report is None:
        return JsonResponse({'encrypt': "Does not exist"})
    else:
        for file in report.companyfile_set.all():
            if request.POST['file'] == file.cfile.name.split('/')[-1]:
                this_file = file
        for file in report.investorfile_set.all():
            if request.POST['file'] == file.ifile.name.split('/')[-1]:
                this_file = file
        return JsonResponse({'encrypt': this_file.encrypted})


def index(request):
    return HttpResponseRedirect('/home')

account/templates/html5up/companies.html
<!DOCTYPE HTML>
<!--
	TXT by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'account/css/main.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'account/css/ie8.css' %}"/>
<link rel="stylesheet" type="text/css" href="{%static 'account/css/font-awesome.min.css'}" />
<link rel="stylesheet" type="image/jpg" href='{% static "account/banner.jpg" %}'/>
<link rel="stylesheet" type="image/jpg" href='{% static "account/css/images/highlight.jpg" %}'/>
<link rel="stylesheet" type="image/jpg" href='{% static "account/css/images/overlay.jpg" %}'/>

<html>
	<head>
		<title>Lokahi Fintech</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="assets/css/main.css" />
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
		<link rel="stylesheet" href="font-awesome/css/font-awesome.min.css">
	</head>
	<body class="homepage">
		<div id="page-wrapper">

			<!-- Header -->
				<header id="header">
					<div class="logo container">
						<div>
							<h1><a href="index.html" id="logo">Lokahi Fintech</a></h1>
						</div>
					</div>
				</header>

			<!-- Nav -->
				<nav id="nav">
					<ul>
						<li class="current"><a href={% url 'loggedin' %}>Home</a></li>
						<li><a href=>Reports</a></li>
						<li><a href = {% url 'groups' %}>Groups</a></li>
						<li><a href= {% url 'logout' %}>LOG OUT</a></li>
					</ul>
				</nav>

			<!-- Banner -->
			<div id="banner-wrapper" style="background-image: url('{% static "account/banner.jpg"%}')">
					<section id="banner" style="background-image: url('{% static "account/css/images/overlay.jpg"%}'), url('{% static "account/css/images/highlight.jpg"%}') "> 
						<h2>Companies</h2>
					</section>
				</div>

			<!-- Main -->
				<div id="main-wrapper">
					<div id="main" class="container">
						<!-- <div class="row 200%">
							<div class="12u">-->

								<!-- Highlight -->
									<section class="box highlight">
										
										<header>
											<h2>Companies</h2>
										</header>
											<strong>As a Company User</strong> you can:
											<br>
											<br>
												<ul>
													<li>Create reports</li>
													<li>Create a group</li>
													<li>Be invited to join a group</li>
												</ul>
									</section>
									

							</div>
						</div>
						
					<footer id="footer">
					<!-- Copyright -->
							<ul class="copyright">
								<li>&copy; Lokahi Fintech. All rights reserved</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
							</ul>
						</div>

				</footer>

			</div>
			

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.dropotron.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/skel-viewport.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>

	</body>
</html>

account/templates/html5up/create_report.html
<!DOCTYPE HTML>
<!--
	TXT by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Lokahi Fintech</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="assets/css/main.css" />
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
		<link rel="stylesheet" href="font-awesome/css/font-awesome.min.css">
	</head>
	<body class="homepage">
		<div id="page-wrapper">

			<!-- Header -->
				<header id="header">
					<div class="logo container">
						<div>
							<h1><a href="create_report.html" id="logo">Create a new Report Page</a></h1>
						</div>
					</div>
				</header>

			<!-- Nav -->
				<nav id="nav">
					<ul>
						<li><a href="company.html">Company Home</a></li>
						<li class = "current"><a href = "reports.html">Reports</a></li>
						<li><a href= "logout.html">LOG OUT</a></li>
					</ul>
				</nav>
			<!-- Three -->
				<section class="wrapper style3 container">

					<!-- Registration form -->

						<div id="content">

							<div class="signup-wrapper">

						          <form class="form-horizontal" id="regForm" method="post">
						  
						            <!-- Company Name input-->
						            <div class="form-group">
						            	<label class="col-md-3 control-label" for="company_name">Company Name</label>
						            	<input id="name" type="text" name="name" placeholder="Your company name" class="form-control required">
						            </div>
						            <!-- Company Phone input-->
						            <div class="form-group">
						            	<label class="col-md-3 control-label" for="company_phone">Company Phone Number</label>
						            	<input id="company_phone" type="text" name="company_phone" placeholder="Your company phone number " class="form-control required">
						            </div>
						            <!-- Company Location input-->
						            <div class="form-group">
						            	<label class="col-md-3 control-label" for="company_location">Company Location</label>
						            	<input id="company_location" type="text" name="company_location" placeholder="Your company location" class="form-control required">
						            </div>
						            <!-- Company Country input-->
						            <div class="form-group">
						            	<label class="col-md-3 control-label" for="company_country">Company Country</label>
						            	<input id="company_country" type="text" name="company_country" placeholder="Your company name" class="form-control required">
						            </div>
						            <!-- Sector input -->
						            <div class="form-group">
						            	<label class="col-md-3 control-label" for="sector">Sector</label>
						            	<input id="sector" type="text" name="sector" placeholder="Sector" class="form-control required">
						            </div>
						            <!-- industry input -->
						            <div class="form-group">
						            	<label class="col-md-3 control-label" for="industry">Industry</label>
						            	<input id="industry" type="text" name="industry" placeholder = "Industry" class="form-control required">
						            </div>
						             <!-- Current Projects input -->
						            <div class="form-group">
						            		<label class="col-md-3 control-label" for="current_projects">Current Projects</label>
						            		<textarea rows="4" cols="50" type = "text" name = "current_projects" placeholder = "Current Projects" class = "form-control required"></textarea>
						            </div>
						             <!-- File Attachments -->
						            <div class="form-group">
						            		<label class="col-md-3 control-label" for="current_projects">File Attachments</label>
						            		<form action="">
											<input type="file" name="fileupload" value="fileupload" id="fileupload">
						            <br>
						            <br>
						            <div style="text-align:center;">
									    <button><a href = "#"><font color = "white">Submit</font></a></button>
									</div>
				<footer id="footer">

						<ul class="icons">
						</ul>
					<!-- Copyright -->
							<ul class="copyright">
								<li>&copy; Lokahi Fintech. All rights reserved</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
							</ul>
						</div>

				</footer>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.dropotron.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/skel-viewport.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>

	</body>
</html>

account/templates/html5up/sitemanager.html
<!DOCTYPE HTML>
<!--
	TXT by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'account/css/main.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'account/css/ie8.css' %}"/>
<link rel="stylesheet" type="text/css" href="{%static 'account/css/font-awesome.min.css'}" />
<link rel="stylesheet" type="image/jpg" href='{% static "account/banner.jpg" %}'/>
<link rel="stylesheet" type="image/jpg" href='{% static "account/css/images/highlight.jpg" %}'/>
<link rel="stylesheet" type="image/jpg" href='{% static "account/css/images/overlay.jpg" %}'/>

<html>
	<head>
		<title>Lokahi Fintech</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="assets/css/main.css" />
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
		<link rel="stylesheet" href="font-awesome/css/font-awesome.min.css">
	</head>
	<body class="homepage">
		<div id="page-wrapper">

			<!-- Header -->
				<header id="header">
					<div class="logo container">
						<div>
							<h1><a href="index.html" id="logo">Lokahi Fintech</a></h1>
						</div>
					</div>
				</header>

			<!-- Nav -->
				<nav id="nav">
					<ul>
						<li class="current"><a href={% url 'loggedin' %}>Home</a></li>
						<li><a href="{% url 'reports:index'%}">Reports</a></li>
						<li><a href = {% url 'groups' %}>Groups</a></li>
						<li><a href={% url 'messaging'%}>Messaging</a><li>
						<li><a href= {% url 'logout' %}>LOG OUT</a></li>
					</ul>
				</nav>

			<!-- Banner -->
			<div id="banner-wrapper" style="background-image: url('{% static "account/banner.jpg"%}')">
					<section id="banner" style="background-image: url('{% static "account/css/images/overlay.jpg"%}'), url('{% static "account/css/images/highlight.jpg"%}') "> 
						<h2>Site Manager</h2>
					</section>
				</div>

			<!-- Main -->
				<div id="main-wrapper">
					<div id="main" class="container">
						<!-- <div class="row 200%">
							<div class="12u">-->

								<!-- Highlight -->
									<section class="box highlight">
										
										<header>
											<h2>Welcome, {{ user.get_username }}</h2>
										</header>
										<h3> You are a Site Manager</h3>
										<br>
										<br>
										<form action="/suspendUser/" method = "POST"> {% csrf_token %}
										    <div style = "padding-left: 80px; float:left; width: 700px;"><input type= text name = "username" id="username" required></div>
										    <div style = "padding-left: 100px; float:left"><input type = submit value = "Suspend/Reactivate User"> </input></div>
										</form>
										<br>
										<br>
										<br>
										<form action="/makeSiteManager/" method = "POST"> {% csrf_token %}
										    <div style = "padding-left: 80px; float:left; width: 700px;"><input type= text name = "username" id="username" required></div>
										    <div style = "padding-left: 100px; float:left"><input type = submit value = "Make User SM"> </input></div>
										</form>
										<br>
										<br>
										<br>
										<form action="/revokeSm/" method = "POST"> {% csrf_token %}
										   <div style = "text-align: center"><input type = submit value = "Revoke SM Status"> </input></div>
										</form>

                                        <br>
									</div>
										<div style = "text-align: center;">
										<h2>{% for message in messages %}
										    <li class="{{ message.tags }}">
										    {% if 'safe' in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}
										    </li>
										    <br>
										    <br>
										{% endfor %}</h2>	</div>								</div>
                                        <br>
										<br>
									<footer id="footer">
					<!-- Copyright -->
							<ul class="copyright">
								<li>&copy; Lokahi Fintech. All rights reserved</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
							</ul>
						</div>

				</footer>

			</div>
			

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.dropotron.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/skel-viewport.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>

	</body>
</html>